### ISSUE TITLE
Needs explicit deps on @org_chromium_libcxx

### ISSUE THREAD

**Issue by nicolov** [vsco/bazel-toolchains#7]
Hey there, thanks for the great work here.

I was wondering how to stop having to depend on `'@org_chromium_libcxx//:cxx',` and `:cxxabi` in each `cc_library` rule. It seems pretty tiresome to me. Custom macros are an option, but I was wondering if there was a way to add it to the CROSSTOOL configuration instead.

**Comment by sayrer** [comment]
I agree this is not great.

I haven't figured out how to include these things in the toolchain without triggering a circular dependency. I'll keep thinking about the best way to automate it, though. Suggestions welcome!

**Comment by sayrer** [comment]
Have a proposed fix for this in https://github.com/vsco/bazel-toolchains/pull/12.

LMK if it works for you.

**Comment by sayrer** [comment]
Should be resolved now.
